namespace CoTGEnumNetwork.Enums
{
    public enum BasicAttackTypes
    {
        SPELLS_BASICATTACKSLOT1 = 0x40,
        SPELLS_BASICATTACKSLOT2 = 0x41,
        SPELLS_BASICATTACKSLOT3 = 0x42,
        SPELLS_BASICATTACKSLOT4 = 0x43,
        SPELLS_BASICATTACK_CRITICAL_SLOT = 0x44,
        SPELLS_BASIC_ATTACK_MISS_SLOT = 0x45,
        SPELLS_BASIC_ATTACK_DODGE_SLOT = 0x46,
        SPELLS_BASIC_ATTACK_TYPES_MAX_SLOT = 0x47
    }
}
