using System;


namespace CrystalSlash
{

    /*
    * Game packet IDs
    * BID = bi-directional, C2S = client to server, S2C = server to cliet, UNK = unknown yet
    */
    public enum GamePacketIDabtest
    {
        BID_Dummy = 0x0,
        UNK_ClientConnect_NamedPipe = 0x1,
        UNK_CHAT = 0x2,
        C2S_QueryStatusReq = 0x3,
        S2C_QueryStatusAns = 0x4,
        S2C_StartSpawn = 0x5,
        S2C_CreateHero = 0x6,
        S2C_CreateNeutral = 0x7,
        S2C_CreateTurret = 0x8,
        S2C_PlayAnimation = 0x9,
        C2S_PlayEmote = 0xA,
        S2C_PlayEmote = 0xB,
        S2C_EndSpawn = 0xC,
        S2C_StartGame = 0xD,
        S2C_EndGame = 0xE,
        C2S_CharSelected = 0xF,
        C2S_ClientReady = 0x10,
        C2S_ClientFinished = 0x11,
        C2S_NPC_UpgradeSpellReq = 0x12,
        S2C_NPC_UpgradeSpellAns = 0x13,
        C2S_NPC_IssueOrderReq = 0x14,
        S2C_FX_Create_Group = 0x15,
        S2C_FX_Kill = 0x16,
        S2C_UnitApplyDamage = 0x17,
        S2C_Pause = 0x18,
        C2S_MapPing = 0x19,
        S2C_MapPing = 0x1A,
        S2C_UnitAddGold = 0x1B,
        S2C_UnitAddEXP = 0x1C,
        UNK_UserMessagesStart = 0x1D,
        S2C_NPC_MessageToClient = 0x1E,
        C2S_AI_Command = 0x1F,
        S2C_CHAR_SpawnPet = 0x20,
        S2C_CHAR_SetCooldown = 0x21,
        S2C_NPC_Die = 0x22,
        S2C_NPC_ForceDead = 0x23,
        C2S_NPC_CastSpellReq = 0x24,
        S2C_NPC_CastSpellAns = 0x25,
        S2C_NPC_BuffAdd2 = 0x26,
        S2C_NPC_BuffAddGroup = 0x27,
        S2C_NPC_BuffReplace = 0x28,
        S2C_NPC_BuffReplaceGroup = 0x29,
        S2C_NPC_BuffRemove2 = 0x2A,
        S2C_NPC_BuffRemoveGroup = 0x2B,
        S2C_NPC_SetAutocast = 0x2C,
        S2C_SetItem = 0x2D,
        C2S_BuyItemReq = 0x2E,
        S2C_BuyItemAns = 0x2F,
        C2S_RemoveItemReq = 0x30,
        S2C_RemoveItemAns = 0x31,
        C2S_SwapItemReq = 0x32,
        S2C_SwapItemAns = 0x33,
        S2C_UseItemAns = 0x34,
        S2C_NPC_LevelUp = 0x35,
        S2C_NPC_InstantStop_Attack = 0x36,
        S2C_Barrack_SpawnUnit = 0x37,
        UNK_Turret_Fire = 0x38,
        UNK_Turret_CreateTurret = 0x39,
        pkt32 = 0x3A,
        S2C_Basic_Attack = 0x3B,
        S2C_Basic_Attack_Pos = 0x3C,
        S2C_OnEnterVisiblityClient = 0x3D,
        S2C_OnLeaveVisiblityClient = 0x3E,
        S2C_OnEnterLocalVisiblityClient = 0x3F,
        S2C_OnLeaveLocalVisiblityClient = 0x40,
        C2S_World_SendCamera_Server = 0x41,
        C2S_World_LockCamera_Server = 0x42,
        C2S_SendSelectedObjID = 0x43,
        S2C_UnitApplyHeal = 0x44,
        S2C_MissileReplication = 0x45,
        S2C_ServerTick = 0x46,
        S2C_DampenerSwitch = 0x47,
        S2C_GlobalCombatMessage = 0x48,
        C2S_SynchVersion = 0x49,
        S2C_SynchVersion = 0x4A,
        S2C_AI_Target = 0x4B,
        S2C_AI_TargetHero = 0x4C,





        /* that's all packet to implement for "cheat" directly from client so for moment we will use an blank packet
        ReloadScripts = 0x4D,
        CheatPacketsBegin = 0x4E,
        CheatUnitAddExperience = 0x4F,
        CheatToggleCallForHelp = 0x50,
        CheatUnitAddGold = 0x51,
        CheatUnitAddHealth = 0x52,
        CheatUnitAddMana = 0x53,
        CheatDamageUnit = 0x54,
        CheatDestroyUnit = 0x55,
        CheatGiveAvatarSpell = 0x56,
        CheatUnitStun = 0x57,
        CheatUnitClearBuffs = 0x58,
        CheatClearCooldowns = 0x59,
        CheatToggleSpectator = 0x5A,
        CheatToggleInvulnerable = 0x5B,
        CheatToggleTargetInvulnerable = 0x5C,
        CheatSpawnMinionC2S = 0x5D,
        CheatSpawnMinionS2C = 0x5E,
        CheatSpawnBotC2S = 0x5F,
        CheatSpawnBotS2C = 0x60,
        CheatBarrackTurnOnOff = 0x61,
        CheatKillTurrets = 0x62,
        CheatMakeMinionsInvulnerable = 0x63,
        CheatTeleport = 0x64,
        CheatSetRespawnTime = 0x65,
        CheatFoW_LocalCulling = 0x66,
        CheatFOW_ServerBroadcastAll = 0x67,
        CheatChangePlayerHero = 0x68,
        CheatRunTest = 0x69,
        CheatRunBVT = 0x6A,
        C2S_PlayAnimation = 0x6B,
        CheatDebugPoint = 0x6C,
        Cheat_StepTime = 0x6D,
        Cheat_Pause_Toggle = 0x6E,
        Cheat_IncTime = 0x6F,
        Cheat_DecTime = 0x70,
        Cheat_ResetGameC2S = 0x71,
        Cheat_ResetTurretS2C = 0x72,
        Chear_DestroyHero = 0x73,
        Cheat_DestroyHero = 0x74,
        Cheat_ResetLevel_Client = 0x75,
        CheatPacketsEnd = 0x76,
        */

       

        S2C_SPM_HierarchicalProfilerUpdate = 0x77,
        S2C_SPM_HierarchicalMemoryUpdate = 0x78,
        S2C_SPM_HierarchicalBBProfileUpdate = 0x79,
        S2C_SPM_SamplingProfilerUpdate = 0x7A,
        C2S_SPM_AddBBProfileListener = 0x7B,
        C2S_SPM_RemoveBBProfileListener = 0x7C,
        S2C_HeroReincarnateAlive = 0x7D,
        S2C_HeroReincarnate = 0x7E,
        S2C_Building_Die = 0x7F,
        S2C_SynchSimTime = 0x80,
        C2S_SynchSimTime = 0x81,
        S2C_SyncSimTimeFinal = 0x82,
        S2C_WaypointList = 0x83,
        S2C_WaypointListHeroWithSpeed = 0x84,
        S2C_ServerGameSettings = 0x85,
        S2C_NPC_BuffUpdateCount = 0x86,
        S2C_NPC_BuffUpdateCountGroup = 0x87,
        C2S_PlayEmoticon = 0x88,
        S2C_PlayEmoticon = 0x89,
        S2C_AvatarInfo_Server = 0x8A,
        S2C_RemovePerceptionBubble = 0x8B,
        S2C_AddUnitPerceptionBubble = 0x8C,
        S2C_AddPosPerceptionBubble = 0x8D,
        S2C_SpawnMinion = 0x8E,
        S2C_StopAnimation = 0x8F,
        S2C_ShowHealthBar = 0x90,
        S2C_UpdateGoldRedirectTarget = 0x91,
        S2C_ChangeCharacterData = 0x92,
        S2C_PopCharacterData = 0x93,
        S2C_PopAllCharacterData = 0x94,
        S2C_FaceDirection = 0x95,
        S2C_CameraBehavior = 0x96,
        C2S_SPM_AddListener = 0x97,
        C2S_SPM_RemoveListener = 0x98,
        C2S_SPM_AddMemoryListener = 0x99,
        C2S_SPM_RemoveMemoryListener = 0x9A,
        S2C_DestroyClientMissile = 0x9B,
        S2C_ChainMissileSync = 0x9C,
        S2C_MissileReplication_ChainMissile = 0x9D,
        S2C_BotAI = 0x9E,
        S2C_AI_TargetSelection = 0x9F,
        S2C_AI_State = 0xA0,
        S2C_OnEvent = 0xA1,
        UNK_OnDisconnected = 0xA2,
        S2C_World_SendCamera_Server_Ack = 0xA3,
        S2C_World_SendGameNumber = 0xA4,
        S2C_NPC_Die_EventHistory = 0xA5,
        C2S_Ping_Load_Info = 0xA6,
        S2C_Ping_Load_Info = 0xA7,
        C2S_Exit = 0xA8,
        S2C_Exit = 0xA9,
        C2S_Reconnect = 0xAA,
        S2C_Reconnect = 0xAB,
        S2C_Reconnect_Done = 0xAC,
        C2S_Waypoint_Acc = 0xAD,
        S2C_WaypointGroup = 0xAE,
        S2C_WaypointGroupWithSpeed = 0xAF,
        S2C_Connected = 0xB0,
        S2C_ToggleInputLockingFlag = 0xB1,
        S2C_ToggleFoW = 0xB2,
        S2C_ToggleFoWOn = 0xB3,
        S2C_SetCircularCameraRestriction = 0xB4,
        S2C_LockCamera = 0xB5,
        S2C_OnReplication = 0xB6,
        C2S_OnReplication_Acc = 0xB7,
        S2C_MoveCameraToPoint = 0xB8,
        S2C_PlayTutorialAudioEvent = 0xB9,
        S2C_ChangeSlotSpellType = 0xBA,
        BID_PausePacket = 0xBB,
        BID_ResumePacket = 0xBC,
        S2C_SetFrequency = 0xBD,
        S2C_SetFadeOut_Push = 0xBE,
        S2C_SetFadeOut_Pop = 0xBF,
        S2C_CreateUnitHighlight = 0xC0,
        S2C_RemoveUnitHighlight = 0xC1,
        S2C_OpenTutorialPopup = 0xC2,
        C2S_OnTutorialPopupClosed = 0xC3,
        S2C_OpenAFKWarningMessage = 0xC4,
        S2C_CloseShop = 0xC5,
        S2C_SetInputLockingFlag = 0xC6,
        C2S_OnShopOpened = 0xC7,
        S2C_ShowObjectiveText = 0xC8,
        S2C_HideObjectiveText = 0xC9,
        S2C_RefreshObjectiveText = 0xCA,
        S2C_ShowAuxiliaryText = 0xCB,
        S2C_HideAuxiliaryText = 0xCC,
        S2C_RefreshAuxiliaryText = 0xCD,
        S2C_HighlightHUDElement = 0xCE,
        S2C_HighlightShopElement = 0xCF,
        C2S_TeamSurrenderVote = 0xD0,
        S2C_TeamSurrenderVote = 0xD1,
        S2C_TeamSurrenderCountDown = 0xD2,
        S2C_TeamSurrenderStatus = 0xD3,
        S2C_LineMissileHitList = 0xD4,
        C2S_TutorialAudioEventFinished = 0xD5,
        S2C_HighlightTitanBarElement = 0xD6,
        S2C_ToggleUIHighlight = 0xD7,
        S2C_DisplayLocalizedTutorialChatText = 0xD8,
        S2C_ToolTipVars = 0xD9,
        S2C_MuteVolumeCategory = 0xDA,
        S2C_OnEventWorld = 0xDB,
        S2C_AnimatedBuildingSetCurrentSkin = 0xDC,
        S2C_SetGreyscaleEnabledWhenDead = 0xDD,
        S2C_DisableHUDForEndOfGame = 0xDE,
        S2C_ChangeSlotSpellName = 0xDF,
        S2C_SwitchNexusesToOnIdleParticles = 0xE0,
        S2C_FadeMinions = 0xE1,
        S2C_FadeOutMainSFX = 0xE2,
        S2C_HeroStats = 0xE3,
        S2C_SetAnimStates = 0xE4,
        C2S_ClientCheatDetectionSignal = 0xE5,
        S2C_AddDebugCircle = 0xE6,
        S2C_RemoveDebugCircle = 0xE7,
        S2C_ModifyDebugCircleRadius = 0xE8,
        S2C_ModifyDebugCircleColor = 0xE9,
        UNK_Undefined = 0xEA,
        S2C_Neutral_Camp_Empty = 0xEB,
        S2C_ResetForSlowLoader = 0xEC,
        Batch = 0xFF,
        UpperLimitForPacketIDs = 0x100,







        //doesnt exit : 

        ExtendedPacket = 0x0FE, //


        C2S_AntiBot = 0x10000,
        C2S_AntiBotDP = 0x10001,
        C2S_OnQuestEvent = 0x10002,
        C2S_OnRespawnPointEvent = 0x10003,
        C2S_OnScoreBoardOpened = 0x10004,
        C2S_OnTipEvent = 0x10005,
        C2S_StatsUpdateReq = 0x10006,
        C2S_UseObject = 0x10007,
        C2S_WriteNavFlags_Acc = 0x10008,
        S2C_WriteNavFlags = 0x10009,
        S2C_AntiBot = 0x1000A,
        S2C_AntiBotWriteLog = 0x1000B,
        S2C_AntiBotKickOut = 0x1000C,
        S2C_AntiBotBanPlayer = 0x1000D,
        S2C_AntiBotTrojan = 0x1000E,
        S2C_AntiBotCloseClient = 0x1000F,

        S2C_AttachFlexParticle = 0x20000,
        S2C_ChangeSlotSpellIcon = 0x20001,              
        S2C_ChangeSlotSpellOffsetTarget = 0x20002,
        S2C_ChangeCharacterVoice = 0x20003,
        S2C_ChangePARColorOverride = 0x20004,
        S2C_CHAR_CancelTargetingReticle = 0x20005,
        UNK_Unused_0C = 0x20006,
        S2C_UpdateLevelProp = 0x20007,
        S2C_UnitChangeTeam = 0x20008,                   
        S2C_UnitSetMinimapIcon = 0x20009 ,
        S2C_SyncMissionStartTime = 0x2000A ,
        S2C_ColorRemapFX = 0x2000B,
        S2C_DisplayFloatingText = 0x2000C,
        S2C_EndOfGameEvent = 0x2000D,
        S2C_FX_OnEnterTeamVisiblity = 0x2000E,
        S2C_FX_OnLeaveTeamVisiblity = 0x2000F   ,

        S2C_IncrementPlayerScore     = 30001 ,
        S2C_IncrementPlayerStat = 30002,
        S2C_LevelUpSpell = 30003,
        S2C_ModifyShield = 30004,
        S2C_MusicCueCommand = 30005,
        S2C_OnEnterTeamVisiblity = 30006,
        S2C_OnLeaveTeamVisiblity = 30007,

        S2C_PauseAnimation = 30008,
        S2C_ReplayOnly_GoldEarned = 30009, 


        S2C_HandleCapturePointUpdate = 0x3000A            /* = 0x0DC */, // xxxx unused in replay      yep dominion
        S2C_HandleGameScore = 0x3000B                       /* = 0x0DD */, // xxxx unused in replay      yep dominion
        S2C_HandleRespawnPointUpdate = 0x3000C ,
        S2C_HandleQuestUpdate = 0x3000D,
        S2C_HandleTipUpdate = 0x3000E ,
        S2C_HandleUIHighlight = 0x3000F,

        S2C_SetCircularMovementRestriction = 40001 ,
        S2C_SetFoWStatus = 40002,
        S2C_SetSpellData = 40003,
        S2C_SpawnBot = 40004,
        S2C_SpawnLevelProp = 40005,
            S2C_NPC_Hero_Die = 40006,
        S2C_PlayVOAudioEvent = 40007,



        //from other version
        S2C_CreateHero_131 = 40008,
        S2C_CreateTurret_131 = 40009,
        S2C_SynchVersion_131 = 40010

    }

}
