global using static System.MathF;
global using static ChildrenOfTheGraveEnumNetwork.Content.HashFunctions;
global using static ChildrenOfTheGrave.ChildrenOfTheGraveServer.API.GameAnnouncementManager;
global using static ChildrenOfTheGrave.ChildrenOfTheGraveServer.API.ApiFunctionManager;
global using static ChildrenOfTheGrave.ChildrenOfTheGraveServer.Scripting.Lua.Functions;
global using static ChildrenOfTheGrave.ChildrenOfTheGraveServer.API.ApiMapFunctionManager;
global using Time = ChildrenOfTheGrave.ChildrenOfTheGraveServer.Game.Time;
global using Buffs;
global using System;
global using System.Linq;
global using CharScripts;
global using ChildrenOfTheGraveEnumNetwork;
global using System.Numerics;
global using MapScripts.Mutators;
global using MapScripts.GameModes;
global using ChildrenOfTheGraveEnumNetwork.Enums;
global using ChildrenOfTheGraveEnumNetwork.Domain;
global using System.Collections.Generic;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.API;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.Content;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.Scripting.CSharp;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.SpellNS;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.StatsNS;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.Scripting.CSharp.Converted;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.SpellNS.Missile;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.AttackableUnits;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.AttackableUnits.AI;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.AttackableUnits.Buildings;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.AttackableUnits.Buildings.Barracks;
global using ChildrenOfTheGrave.ChildrenOfTheGraveServer.GameObjects.AttackableUnits.Buildings.AnimatedBuildings;