namespace ChildrenOfTheGraveEnumNetwork.Packets.Enums
{
    public enum CheatIDEnum
    {
        Cheat_UnitAddExperience = 0x0,
        Cheat_UnitAddGold = 0x1,
        Cheat_UnitAddHealth = 0x2,
        Cheat_UnitAddMana = 0x3,
        Cheat_DamageUnit = 0x4,
        Cheat_DestroyUnit = 0x5,
        Cheat_UnitStun = 0x6,
        Cheat_ClearCooldowns = 0x7,
        Cheat_ToggleInvulnerable = 0x8,
        Cheat_ToggleTargetInvulnerable = 0x9,
        Cheat_ToggleTargetTeam = 0xA,
        Cheat_SpawnMinionC2S = 0xB,
        Cheat_SpawnMinionS2C = 0xC,
        Cheat_SpawnBotC2S = 0xD,
        Cheat_SpawnBotS2C = 0xE,
        Cheat_BarrackTurnOnOff = 0xF,
        Cheat_MakeMinionsInvulnerable = 0x10,
        Cheat_Teleport = 0x11,
        Cheat_SetRespawnTime = 0x12,
        Cheat_FoW_LocalCulling = 0x13,
        Cheat_ChangePlayerHero = 0x14,
        Cheat_StepTime = 0x15,
        Cheat_Pause_Toggle = 0x16,
        Cheat_IncTime = 0x17,
        Cheat_DecTime = 0x18,
        Cheat_DestroyHero = 0x19,
        Cheat_ResetGameC2S = 0x1A,
        Cheat_ResetLevel_Client = 0x1B,
        Cheat_ResetGui_Client = 0x1C,
        Cheat_ResetTurretS2C = 0x1D,
        Cheat_FinishGame = 0x1E,
        Cheat_FramerateLogC2S = 0x1F,
        Cheat_FramerateLogS2C = 0x20,
        Cheat_RunTest = 0x21,
        Cheat_GiveAvatarSpell = 0x22,
        Cheat_ToggleCallForHelp = 0x23,
        Cheat_UnitClearBuffs = 0x24,
        Cheat_ToggleSpectator = 0x25,
        Cheat_KillTurrets = 0x26,
        Cheat_FOW_ServerBroadcastAll = 0x27,
        Cheat_C2S_PlayAnimation = 0x28,
        Cheat_DebugPoint = 0x29,
        Cheat_RunBVT = 0x2A,
    }
}
