using System;


namespace SiphoningStrike
{

    /*
    * Game packet IDs
    * BID = bi-directional, C2S = client to server, S2C = server to cliet, UNK = unknown yet
    */
    public enum GamePacketID                     // packetID    Jobs-RE  CheckReplay        present_in_notifier/handler
    {
        BID_Dummy                                /* = 0x000 */, // Done
        S2C_SPM_HierarchicalProfilerUpdate       /* = 0x001 */, // Done  //complete           nope
        S2C_DisplayLocalizedTutorialChatText     /* = 0x002 */, // Done  //complete           nope
        S2C_Barrack_SpawnUnit                    /* = 0x003 */, // Done  //complete           yep
        S2C_SwitchNexusesToOnIdleParticles       /* = 0x004 */, // Done  //complete           nope
        C2S_TutorialAudioEventFinished           /* = 0x005 */, // Done  //complete           nope
        S2C_SetCircularMovementRestriction       /* = 0x006 */, // xxxx unused in replay      yep for dominion
        S2C_UpdateGoldRedirectTarget             /* = 0x007 */, // Done //complete
        C2S_SynchSimTime                         /* = 0x008 */, // xxxx unused in replay      yep
        C2S_RemoveItemReq                        /* = 0x009 */, // xxxx unused in replay      yep
        BID_ResumePacket                         /* = 0x00A */, // xxxx unused in replay      unk
        S2C_RemoveItemAns                        /* = 0x00B */, // Done //complete            yep
        UNK_Unused_0C                            /* = 0x00C */, // xxxx unused in replay      unk
        S2C_Basic_Attack                         /* = 0x00D */, // Done //complete            yep
        S2C_RefreshObjectiveText                 /* = 0x00E */, // xxxx unused in replay      nope needed for some gamemode
        S2C_CloseShop                            /* = 0x00F */, // Done //complete            nope
        S2C_Reconnect                            /* = 0x010 */, // xxxx unused in replay      unk
        S2C_UnitAddEXP                           /* = 0x011 */, // Done //complete            yep
        S2C_EndSpawn                             /* = 0x012 */, // Done  //complete           yep
        S2C_SetFrequency                         /* = 0x013 */, // xxxx unused in replay      unk
        S2C_HighlightTitanBarElement             /* = 0x014 */, // xxxx unused in replay      nope needed for some gamemode
        S2C_BotAI                                /* = 0x015 */, // xxxx unused in replay      nope needed for some gamemode
        S2C_TeamSurrenderCountDown               /* = 0x016 */, // xxxx unused in replay      nope needed for some gamemode
        C2S_QueryStatusReq                       /* = 0x017 */, // xxxx unused in replay      yep
        S2C_NPC_UpgradeSpellAns                  /* = 0x018 */, // Done //complete            yep
        C2S_Ping_Load_Info                       /* = 0x019 */, // xxxx  not replay //strange  yep
        S2C_ChangeSlotSpellType                  /* = 0x01A */, // xxxx not replay //strange  yep
        S2C_NPC_MessageToClient                  /* = 0x01B */, // Done //complete ( nostring? ) nope ( or somewhere else ) 
        S2C_DisplayFloatingText                  /* = 0x01C */, // xxxx  unused in replay      nope needed for some gamemode
        S2C_Basic_Attack_Pos                     /* = 0x01D */, // Done //complete            yep
        S2C_NPC_ForceDead                        /* = 0x01E */, // xxxx unused in replay      nope needed for cheat ? 
        S2C_NPC_BuffUpdateCount                  /* = 0x01F */, // Done //complete            yep
        C2S_WriteNavFlags_Acc                    /* = 0x020 */, // xxxx unused in replay      nope BUT Really important for nav 
        S2C_NPC_BuffReplaceGroup                 /* = 0x021 */, // xxxx not replay //strange  nope ( but possibly send 3 time single does the same ) 
        S2C_NPC_SetAutocast                      /* = 0x022 */, // xxxx unused in replay      yep
        C2S_SwapItemReq                          /* = 0x023 */, // xxxx unused in replay      yep
        S2C_NPC_Die_EventHistory                 /* = 0x024 */, // NOPE this one is broken in ss in all case  
        S2C_UnitAddGold                          /* = 0x025 */, // Done //complete            yep
        S2C_AddUnitPerceptionBubble              /* = 0x026 */, // Done  //complete           yep
        S2C_MoveCameraToPoint                    /* = 0x027 */, // xxxx unused in replay      yep
        S2C_LineMissileHitList                   /* = 0x028 */, // xxxx unused in replay      yep
        S2C_MuteVolumeCategory                   /* = 0x029 */, // xxxx unused in replay      nope
        S2C_ServerTick                           /* = 0x02A */, // xxxx unused in replay      unk
        S2C_StopAnimation                        /* = 0x02B */, // Done //complete            yep
        S2C_AvatarInfo_Server                    /* = 0x02C */, // Done  //complete           yep
        S2C_DampenerSwitch                       /* = 0x02D */, // Done //complete            yep
        S2C_World_SendCamera_Server_Ack          /* = 0x02E */, // xxxx unused in replay      yep
        S2C_ModifyDebugCircleRadius              /* = 0x02F */, // xxxx unused in replay      yep for dominion
        C2S_World_SendCamera_Server              /* = 0x030 */, // xxxx unused in replay      yep
        S2C_HeroReincarnateAlive                 /* = 0x031 */, // Done //complete            yep
        S2C_NPC_BuffReplace                      /* = 0x032 */, // Done //COMPLETE            yep
        S2C_Pause                                /* = 0x033 */, // xxxx unused in replay      yep
        S2C_SetFadeOut_Pop                       /* = 0x034 */, // xxxx unused in replay      nope ??? 
        S2C_ChangeSlotSpellName                  /* = 0x035 */, // Done //COMPLETE            yep need verif
        S2C_ChangeSlotSpellIcon                  /* = 0x036 */, // xxxx unused in replay      yep need verif
        S2C_ChangeSlotSpellOffsetTarget          /* = 0x037 */, // xxxx unused in replay      yep need verif
        S2C_RemovePerceptionBubble               /* = 0x038 */, // Done //COMPLETE            yep
        S2C_NPC_InstantStop_Attack               /* = 0x039 */, // Done  //complete           yep need verif
        S2C_OnLeaveLocalVisiblityClient          /* = 0x03A */, // Done  //unused in replay ? STRANGE 
        S2C_ShowObjectiveText                    /* = 0x03B */, // xxxx unused in replay      yep for gamemode
        S2C_CHAR_SpawnPet                        /* = 0x03C */, // xxxx unused in replay      yep
        S2C_FX_Kill                              /* = 0x03D */, // Done //COMPLETE            yep
        C2S_NPC_UpgradeSpellReq                  /* = 0x03E */, // xxxx unused in replay      yep
        C2S_UseObject                            /* = 0x03F */, // xxxx unused in replay      yep
        UNK_Turret_CreateTurret                  /* = 0x040 */, // xxxx unused in replay      possibly large bit at start of replay represent this one
        S2C_MissileReplication                   /* = 0x041 */, // Done //COMPLETE            yep
        S2C_ResetForSlowLoader                   /* = 0x042 */, // xxxx unused in replay      nope
        S2C_HighlightHUDElement                  /* = 0x043 */, // xxxx unused in replay      yep for gamemode
        S2C_SwapItemAns                          /* = 0x044 */, // Done //complete            yep
        S2C_NPC_LevelUp                          /* = 0x045 */, // Done //complete            yep
        S2C_MapPing                              /* = 0x046 */, // Done //complete            yep
        S2C_WriteNavFlags                        /* = 0x047 */, // xxxx unused in replay      nope BUT Really important for nav 
        S2C_PlayEmote                            /* = 0x048 */, // Done //complete            yep
        S2C_Reconnect_Done                       /* = 0x049 */, // xxxx unused in replay      yep
        S2C_OnEventWorld                         /* = 0x04A */, // Done //complete            yep
        S2C_HeroStats                            /* = 0x04B */, // xxxx unused in replay      yep
        C2S_PlayEmote                            /* = 0x04C */, // xxxx unused in replay      yep
        S2C_HeroReincarnate                      /* = 0x04D */, // Done //complete            nope
        C2S_OnScoreBoardOpened                   /* = 0x04E */, // xxxx unused in replay      yep
        S2C_CreateHero                           /* = 0x04F */, // Done //complete            yep
        C2S_SPM_AddMemoryListener                /* = 0x050 */, // xxxx unused in replay      unk
        S2C_SPM_HierarchicalMemoryUpdate         /* = 0x051 */, // xxxx unused in replay      unk
        S2C_ToggleUIHighlight                    /* = 0x052 */, // xxxx unused in replay      gamemode or debug
        S2C_FaceDirection                        /* = 0x053 */, // Done //complete            yep
        S2C_OnLeaveVisiblityClient               /* = 0x054 */, // xxxx  //unused in replay ? STRANGE 
        C2S_ClientReady                          /* = 0x055 */, // xxxx unused in replay      yep
        S2C_SetItem                              /* = 0x056 */, // xxxx unused in replay      yep
        S2C_SynchVersion                         /* = 0x057 */, // xxxx unused in replay      yep //pretty sur not completed
        S2C_HandleTipUpdate                      /* = 0x058 */, // xxxx unused in replay      yep 
        C2S_StatsUpdateReq                       /* = 0x059 */, // xxxx unused in replay      nope
        C2S_MapPing                              /* = 0x05A */, // xxxx unused in replay      yep 
        S2C_RemoveDebugCircle                    /* = 0x05B */, // xxxx unused in replay      nopee
        S2C_CreateUnitHighlight                  /* = 0x05C */, // xxxx unused in replay      yep debug or gamemode
        S2C_DestroyClientMissile                 /* = 0x05D */, // Done //complete            yep
        S2C_LevelUpSpell                         /* = 0x05E */, // xxxx unused in replay      STRANGE
        S2C_StartGame                            /* = 0x05F */, // Done //complete            yep
        C2S_OnShopOpened                         /* = 0x060 */, // xxxx unused in replay      nope
        S2C_NPC_Hero_Die                         /* = 0x061 */, // Done //complete            yep
        S2C_FadeOutMainSFX                       /* = 0x062 */, // xxxx unused in replay      nope
        UNK_UserMessagesStart                    /* = 0x063 */, // xxxx unused in replay      nope
        S2C_WaypointGroup                        /* = 0x064 */, // Done //complete            yep
        S2C_StartSpawn                           /* = 0x065 */, // xxxx unused in replay      nope
        S2C_CreateNeutral                        /* = 0x066 */, // Done //complete            yep
        S2C_WaypointGroupWithSpeed               /* = 0x067 */, // Done //complete            yep
        S2C_UnitApplyDamage                      /* = 0x068 */, // Done //complete            yep
        S2C_ModifyShield                         /* = 0x069 */, // Done //complete            yep
        S2C_PopCharacterData                     /* = 0x06A */, // Done //complete            nope 
        S2C_NPC_BuffAddGroup                     /* = 0x06B */, // xxxx unused in replay      nope
        S2C_AI_TargetSelection                   /* = 0x06C */, // xxxx unused in replay      nope
        S2C_AI_Target                            /* = 0x06D */, // Done //complete            yep
        S2C_SetAnimStates                        /* = 0x06E */, // xxxx unused in replay      yep
        S2C_ChainMissileSync                     /* = 0x06F */, // xxxx unused in replay      yep
        C2S_OnTipEvent                           /* = 0x070 */, // xxxx unused in replay      yep
        S2C_MissileReplication_ChainMissile      /* = 0x071 */, // xxxx unused in replay      nope
        S2C_BuyItemAns                           /* = 0x072 */, // Done //complete            yep
        S2C_SetSpellData                         /* = 0x073 */, // xxxx unused in replay      yep
        S2C_PauseAnimation                       /* = 0x074 */, // xxxx unused in replay      yep
        C2S_NPC_IssueOrderReq                    /* = 0x075 */, // xxxx unused in replay      yep
        S2C_CameraBehavior                       /* = 0x076 */, // xxxx unused in replay      yep
        S2C_AnimatedBuildingSetCurrentSkin       /* = 0x077 */, // xxxx unused in replay      nope
        S2C_Connected                            /* = 0x078 */, // xxxx unused in replay      unk
        S2C_SyncSimTimeFinal                     /* = 0x079 */, // xxxx unused in replay      unk
        C2S_Waypoint_Acc                         /* = 0x07A */, //  xxxx unused in replay     yep
        S2C_AddPosPerceptionBubble               /* = 0x07B */, // Done //complete            yep
        S2C_LockCamera                           /* = 0x07C */, // xxxx unused in replay      nope
        S2C_PlayVOAudioEvent                     /* = 0x07D */, // xxxx unused in replay      nope 'some spell or anim need them " 
        C2S_AI_Command                           /* = 0x07E */, // xxxx unused in replay      nope 
        S2C_NPC_BuffRemove2                      /* = 0x07F */, // Done //complete            yep
        S2C_SpawnMinion                          /* = 0x080 */, // Done //complete            yep
        C2S_ClientCheatDetectionSignal           /* = 0x081 */, // xxxx unused in replay      nope 
        S2C_ToggleFoW                            /* = 0x082 */, // xxxx unused in replay      nope
        S2C_ToolTipVars                          /* = 0x083 */, // Done //complete            yep
        S2C_UnitApplyHeal                        /* = 0x084 */, // xxxx unused in replay      nope
        S2C_GlobalCombatMessage                  /* = 0x085 */, // xxxx unused in replay      nope
        C2S_World_LockCamera_Server              /* = 0x086 */, // xxxx unused in replay      yep
        C2S_BuyItemReq                           /* = 0x087 */, // xxxx unused in replay      yep
        S2C_WaypointListHeroWithSpeed            /* = 0x088 */, // xxxx unused in replay      yep
        S2C_SetInputLockingFlag                  /* = 0x089 */, // Done //complete            nope
        S2C_CHAR_SetCooldown                     /* = 0x08A */, // Done //complete            yep
        S2C_CHAR_CancelTargetingReticle          /* = 0x08B */, // xxxx unused in replay      nope
        S2C_FX_Create_Group                      /* = 0x08C */, // Done //complete            yep
        S2C_QueryStatusAns                       /* = 0x08D */, // xxxx unused in replay      yep
        S2C_Building_Die                         /* = 0x08E */, // Done //complete            yep
        C2S_SPM_RemoveListener                   /* = 0x08F */, // xxxx unused in replay      nope
        S2C_HandleQuestUpdate                    /* = 0x090 */, // xxxx unused in replay      nope btw quest are not already integrate in LSB 
        C2S_ClientFinished                       /* = 0x091 */, // xxxx unused in replay      nope
        UNK_CHAT                                 /* = 0x092 */, // xxxx unused in replay      STRANGE   
        C2S_SPM_RemoveMemoryListener             /* = 0x093 */, // xxxx unused in replay      nope
        C2S_Exit                                 /* = 0x094 */, // xxxx unused in replay      yep
        S2C_ServerGameSettings                   /* = 0x095 */, // xxxx unused in replay      unk
        S2C_ModifyDebugCircleColor               /* = 0x096 */, // xxxx unused in replay      yep only under tower dominion
        C2S_SPM_AddListener                      /* = 0x097 */, // xxxx unused in replay      nope
        S2C_World_SendGameNumber                 /* = 0x098 */, // xxxx unused in replay      nope ( possibly used only for replay ) 
        S2C_ChangePARColorOverride               /* = 0x099 */, // xxxx unused in replay      nope 
        UNK_ClientConnect_NamedPipe              /* = 0x09A */, // xxxx unused in replay      nope 
        S2C_NPC_BuffRemoveGroup                  /* = 0x09B */, // xxxx unused in replay      nope
        UNK_Turret_Fire                          /* = 0x09C */, // xxxx unused in replay      nope
        S2C_Ping_Load_Info                       /* = 0x09D */, // Done  //complete           yep
        S2C_ChangeCharacterVoice                 /* = 0x09E */, // xxxx unused in replay      nope
        S2C_ChangeCharacterData                  /* = 0x09F */, // Done  //complete           yep
        S2C_Exit                                 /* = 0x0A0 */, // Done //complete            nope 
        C2S_SPM_RemoveBBProfileListener          /* = 0x0A1 */, // xxxx unused in replay      nope
        C2S_NPC_CastSpellReq                     /* = 0x0A2 */, // xxxx unused in replay      yep
        S2C_ToggleInputLockingFlag               /* = 0x0A3 */, // xxxx unused in replay      yep but commentary
        C2S_Reconnect                            /* = 0x0A4 */, // xxxx unused in replay      nope
        S2C_CreateTurret                         /* = 0x0A5 */, // Done //complete            yep
        S2C_NPC_Die                              /* = 0x0A6 */, // Done //complete            yep
        S2C_UseItemAns                           /* = 0x0A7 */, // xxxx unused in replay      yep
        S2C_ShowAuxiliaryText                    /* = 0x0A8 */, // xxxx unused in replay      nope
        BID_PausePacket                          /* = 0x0A9 */, // xxxx unused in replay      unk
        S2C_HideObjectiveText                    /* = 0x0AA */, // xxxx unused in replay      nope
        S2C_OnEvent                              /* = 0x0AB */, // Done //complete            yep
        C2S_TeamSurrenderVote                    /* = 0x0AC */, // xxxx unused in replay      yep
        S2C_TeamSurrenderStatus                  /* = 0x0AD */, // xxxx unused in replay      yep
        C2S_SPM_AddBBProfileListener             /* = 0x0AE */, // xxxx unused in replay      nope
        S2C_HideAuxiliaryText                    /* = 0x0AF */, // xxxx unused in replay      nope
        C2S_OnReplication_Acc                    /* = 0x0B0 */, // xxxx unused in replay      yep
        UNK_OnDisconnected                       /* = 0x0B1 */, // xxxx unused in replay      nope
        S2C_SetGreyscaleEnabledWhenDead          /* = 0x0B2 */, // xxxx unused in replay      yep
        S2C_AI_State                             /* = 0x0B3 */, // xxxx unused in replay      yep
        S2C_SetFoWStatus                         /* = 0x0B4 */, // xxxx unused in replay      nope
#if DEBUG_AB || RELEASE_AB
        UNK_ReloadScripts,
        UNK_Cheat,
#endif
        S2C_OnEnterLocalVisiblityClient          /* = 0x0B5 */, // xxxx //unused in replay ? STRANGE
        S2C_HighlightShopElement                 /* = 0x0B6 */, // xxxx unused in replay      nope tutorial
        C2S_SendSelectedObjID                    /* = 0x0B7 */, // xxxx unused in replay      nope
        S2C_PlayAnimation                        /* = 0x0B8 */, // Done //complete            yep
        S2C_RefreshAuxiliaryText                 /* = 0x0B9 */, // xxxx unused in replay      nope
        S2C_SetFadeOut_Push                      /* = 0x0BA */, // Done //complete            yep
        S2C_OpenTutorialPopup                    /* = 0x0BB */, // xxxx unused in replay      nope tutorial
        S2C_RemoveUnitHighlight                  /* = 0x0BC */, // xxxx unused in replay      yep
        S2C_NPC_CastSpellAns                     /* = 0x0BD */, // Done //complete            yep
        S2C_SPM_HierarchicalBBProfileUpdate      /* = 0x0BE */, // xxxx unused in replay      nope
        S2C_NPC_BuffAdd2                         /* = 0x0BF */, // Done //complete            yep
        S2C_OpenAFKWarningMessage                /* = 0x0C0 */, // xxxx unused in replay      nope
        S2C_WaypointList                         /* = 0x0C1 */, // xxxx unused in replay STRANGE yep
        S2C_OnEnterVisiblityClient               /* = 0x0C2 */, // Done   //COMPLETE          yep
        S2C_AddDebugCircle                       /* = 0x0C3 */, // xxxx unused in replay      nope debug or gamemode
        S2C_DisableHUDForEndOfGame               /* = 0x0C4 */, // Done   //COMPLETE          yep
        C2S_SynchVersion                         /* = 0x0C5 */, // xxxx unused in replay      yep
        C2S_CharSelected                         /* = 0x0C6 */, // xxxx unused in replay      yep
        S2C_NPC_BuffUpdateCountGroup             /* = 0x0C7 */, // xxxx unused in replay      yep
        S2C_AI_TargetHero                        /* = 0x0C8 */, // Done  //complete           yep
        S2C_SynchSimTime                         /* = 0x0C9 */, // Done  //complete           yep
        S2C_SyncMissionStartTime                 /* = 0x0CA */, // xxxx unused in replay      nope quest not integrated on lsb 
        S2C_Neutral_Camp_Empty                   /* = 0x0CB */, // xxxx unused in replay      yep but not complete
        S2C_OnReplication                        /* = 0x0CC */, // Done   //complete          yep
        S2C_EndOfGameEvent                       /* = 0x0CD */, // xxxx unused in replay      nope
        S2C_EndGame                              /* = 0x0CE */, // Done   //complete          yep
        UNK_Undefined                            /* = 0x0CF */, // xxxx unused in replay      nope
        S2C_SPM_SamplingProfilerUpdate           /* = 0x0D0 */, // xxxx unused in replay      nope
        S2C_PopAllCharacterData                  /* = 0x0D1 */, // xxxx unused in replay      nope
        S2C_TeamSurrenderVote                    /* = 0x0D2 */, // xxxx unused in replay      yep 
        S2C_HandleUIHighlight                    /* = 0x0D3 */, // xxxx unused in replay      nope
        S2C_FadeMinions                          /* = 0x0D4 */, // xxxx unused in replay      nope
        C2S_OnTutorialPopupClosed                /* = 0x0D5 */, // xxxx unused in replay      nope Tutorial
        C2S_OnQuestEvent                         /* = 0x0D6 */, // xxxx unused in replay      nope Questsytem not integrate
        S2C_ShowHealthBar                        /* = 0x0D7 */, // xxxx unused in replay      yep
        S2C_SpawnBot                             /* = 0x0D8 */, // xxxx unused in replay      nope ( cheat ? )
        S2C_SpawnLevelProp                       /* = 0x0D9 */, // xxxx unused in replay      yep
        S2C_UpdateLevelProp                      /* = 0x0DA */, // xxxx unused in replay      yep
        S2C_AttachFlexParticle                   /* = 0x0DB */, // xxxx unused in replay      yep dominion
        S2C_HandleCapturePointUpdate             /* = 0x0DC */, // xxxx unused in replay      yep dominion
        S2C_HandleGameScore                      /* = 0x0DD */, // xxxx unused in replay      yep dominion
        S2C_HandleRespawnPointUpdate             /* = 0x0DE */, // xxxx unused in replay      yep dominion
        C2S_OnRespawnPointEvent                  /* = 0x0DF */, // xxxx unused in replay      yep dominion
        S2C_UnitChangeTeam                       /* = 0x0E0 */, // xxxx unused in replay      yep dominion
        S2C_UnitSetMinimapIcon                   /* = 0x0E1 */, // xxxx unused in replay      yep dominion
        S2C_IncrementPlayerScore                 /* = 0x0E2 */, // xxxx unused in replay      yep dominion
        S2C_IncrementPlayerStat                  /* = 0x0E3 */, // xxxx unused in replay      nope dominion
        S2C_ColorRemapFX                         /* = 0x0E4 */, // xxxx unused in replay      yep dominion
        S2C_MusicCueCommand                      /* = 0x0E5 */, // xxxx unused in replay      yep dominion // commentary
        S2C_AntiBot                              /* = 0x0E6 */, // xxxx unused in replay      nope
        S2C_AntiBotWriteLog                      /* = 0x0E7 */, // xxxx unused in replay      nope
        S2C_AntiBotKickOut                       /* = 0x0E8 */, // xxxx unused in replay      nope
        S2C_AntiBotBanPlayer                     /* = 0x0E9 */, // xxxx unused in replay      nope
        S2C_AntiBotTrojan                        /* = 0x0EA */, // xxxx unused in replay      nope
        S2C_AntiBotCloseClient                   /* = 0x0EB */, // xxxx unused in replay      nope
        C2S_AntiBotDP                            /* = 0x0EC */, // xxxx unused in replay      nope
        C2S_AntiBot                              /* = 0x0ED */, // xxxx unused in replay      nope
        S2C_OnEnterTeamVisiblity                 /* = 0x0EE */, // Done  //complete           yep
        S2C_OnLeaveTeamVisiblity                 /* = 0x0EF */, // Done  //complete           yep
        S2C_FX_OnEnterTeamVisiblity              /* = 0x0F0 */, // Done unused in replay   STRANGE     yep
        S2C_FX_OnLeaveTeamVisiblity              /* = 0x0F1 */, // Done unused in replay   STRANGE   yep
        S2C_ReplayOnly_GoldEarned                /* = 0x0F2 */, // Done  //complete           nope

        ExtendedPacket = 0x0FE, //
        Batch = 0x0FF, //
    }
}

