global using static CoTG.CoTGServer.API.GameAnnouncementManager;
global using static CoTG.CoTGServer.API.ApiFunctionManager;
global using static CoTG.CoTGServer.Scripting.Lua.Functions;
global using static CoTG.CoTGServer.API.ApiMapFunctionManager;
global using System;
global using System.Linq;
global using CoTGEnumNetwork;
global using System.Numerics;
global using MapScripts.Mutators;
global using MapScripts.GameModes;
global using CoTGEnumNetwork.Enums;
global using System.Collections.Generic;
global using CoTG.CoTGServer.API;
global using CoTG.CoTGServer.Content;
global using CoTG.CoTGServer.GameObjects;
global using CoTG.CoTGServer.Scripting.CSharp;
global using CoTG.CoTGServer.GameObjects.StatsNS;
global using CoTG.CoTGServer.Scripting.CSharp.Converted;
global using CoTG.CoTGServer.GameObjects.AttackableUnits;
global using CoTG.CoTGServer.GameObjects.AttackableUnits.AI;
